### ISSUE TITLE
Helm chart 2.10 breaks cloud-sql-auth-proxy on google with private ip's.

### ISSUE THREAD

**Issue by brokenjacobs** [pachyderm/pachyderm#10106]
**What happened?**:
Pachyderm failed to start, pgbouncer couldn't connect to the auth proxy and the auth proxy logged:

```
2024/06/06 15:05:02 [-----] failed to connect to instance: Config error: instance does not have IP of type "PUBLIC" (connection name = "-----")
```

(Connection name edited out)

**What you expected to happen?**:
Auth proxy should connect

**How to reproduce it (as minimally and precisely as possible)?**:
Use a private ip with a Cloud sql instance (at Google)

**Anything else we need to know?**:
The cloud sql auth proxy template needs to allow passing the `--private-ip` command line argument. 
See Here: https://github.com/GoogleCloudPlatform/cloud-sql-proxy?tab=readme-ov-file#configuring-private-ip
(This needs to be optional)
I've been able to work around this issue for now using a flux helmrelease postRenderer like so:
```
  postRenderers:
  - kustomize:
      patches:
      - target:
          version: v1
          kind: Deployment
          name: cloudsql-auth-proxy
        patch: |
          apiVersion: apps/v1
          kind: not-used
          metadata:
            name: not-used
          spec:
            template:
              spec:
                containers:
                - name: cloud-sql-proxy
                  args:
                  - --private-ip
```

**Environment?**:
- Kubernetes version (use `kubectl version`): v1.28.9-gke.1000000
- Pachyderm CLI and pachd server version (use `pachctl version`): cli/pachd 2.10.2 / 2.10.2
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s): Google GKE
- If you deployed with helm, the values you used (`helm get values pachyderm`): NA see above
- OS (e.g. from /etc/os-release): google container optimized os
- Others:
