### ISSUE TITLE
Shrink build images and cache on CI

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#2632]
I explored the docker build caching as part of [this PR](https://github.com/pachyderm/pachyderm/pull/2623)

And found:

1) Some existing benchmarks

- our pachyderm_compile image is big (~1.15GB)
- our `docker build -t pachyderm_compile .` step takes about 1m33s (including pulling `ubuntu:14.04` and doing the actual building of this Dockerfile)

2) doing caching as described [here](https://github.com/travis-ci/travis-ci/issues/5358) ... specifically the bit like:

```
before_cache:
  # Save tagged docker images
  - mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}'
    | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz'
before_install:
  # Load cached docker images
  - if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi
cache:
  bundler: true
  directories:
    - $HOME/docker
```
Added 3m to the build time just for downloading this data from the cache on subsequent builds. Which is double the non cached docker build time. Clearly this optimization isn't worth it

3) Future work

If we shrank our `pachyderm_compile` container to be smaller, then this sort of optimization makes more sense. In addition, [this seems to be the recommended way](https://github.com/moby/moby/pull/26839) of caching the actual docker build (not the pulls). But that's only meaningful if the pull doesn't take longer than the non cached build times.
