### ISSUE TITLE
Prometheus annotation serializing incorrectly

### ISSUE THREAD

**Issue by jkinkead** [pachyderm/pachyderm#2968]
The YAML serialization of the prometheus port annotation is generating a bad UTF-8 escape:

```
# From the pachd Service.
metadata:
  annotations:
    prometheus.io/port: "\u9:?:"
```

It's odd that this is using a single unicode character, instead of an integer, but the JSON has:
```
"prometheus.io/port": "⎃"
```
(a single unicode character).

This incorrect serialization results in a parse error from kubectl.
