### ISSUE TITLE
panic: could not intiailize (sic) Pachyderm client in driver: context deadline exceeded

### ISSUE THREAD

**Issue by kevlar1818** [pachyderm/pachyderm#3020]
**What happened?**:

- Create a PV for Minio.
- Install Minio:
```
$ helm install --namespace minio -f minio-values.yml stable/minio
```
- Configure Pachyderm to use Minio backend:
```
# ** excerpt from file pachyderm-values.yml **

## Set default credentials for object store
credentials: "s3"

## S3 endpoint (i.e: Minio server) credentials
s3:
 accessKey: ...
 secretKey: ...
 bucketName: "pachyderm-bucket"
 ## The endpoint should be something like: <mydomain>.<subdomain>:<port>
 endpoint: "my-release-minio.minio:9000"
 ## For 'true' set the value to 1
 secure: "0"
 ## For 'S3v2' signature, set the value to 1. For 'S3v4', set this value to 0
 signature: "1"
```
- Install Pachyderm:
```
$ helm install --namespace pachyderm -f pachyderm-values.yml stable/pachyderm
```
- See that the pachd pod is failing:
```
$ kc logs -n pachyderm pachd-57897d6b69-zcsrz
time="2018-06-27T21:25:07Z" level=error msg="unable to access kubernetes nodeslist, Pachyderm will continue to work but it will not be possible to use COEFFICIENT parallelism. error: nodes is forbidden: User "system:serviceaccount:pachyderm:pachyderm" cannot list nodes at the cluster scope" 
panic: could not intiailize Pachyderm client in driver: context deadline exceeded

goroutine 59 [running]:
github.com/pachyderm/pachyderm/src/server/pfs/server.(*driver).getPachClient.func1()
	/go/src/github.com/pachyderm/pachyderm/src/server/pfs/server/driver.go:173 +0x2d6
sync.(*Once).Do(0xc4203881c0, 0xc4205bef88)
	/usr/local/go/src/sync/once.go:44 +0xbe
github.com/pachyderm/pachyderm/src/server/pfs/server.(*driver).getPachClient(0xc4203881b0, 0x1d93060, 0xc4200400a0, 0xc42010be80)
	/go/src/github.com/pachyderm/pachyderm/src/server/pfs/server/driver.go:169 +0x50
github.com/pachyderm/pachyderm/src/server/pfs/server.newDriver.func3(0xc4203881b0)
	/go/src/github.com/pachyderm/pachyderm/src/server/pfs/server/driver.go:151 +0x43
created by github.com/pachyderm/pachyderm/src/server/pfs/server.newDriver
	/go/src/github.com/pachyderm/pachyderm/src/server/pfs/server/driver.go:151 +0x56b
``` 

**What you expected to happen?**:
The pachd pod shouldn't be failing.

**How to reproduce it (as minimally and precisely as possible)?**:
See above.

**Environment?**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-12T14:14:26Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Pachyderm CLI version (use `pachctl version`): `n/a`
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s): `On-prem Dockerized k8s`
- OS (e.g. from /etc/os-release): Host OS=`Arch Linux`, Kubernetes OS=`Ubuntu 16.04`
