### ISSUE TITLE
pachctl get-logs --job will hang for a pipeline in standby

### ISSUE THREAD

**Issue by mdaniel** [pachyderm/pachyderm#3422]
**What happened?**:

Given a sleeping pipeline, with a "successful" job that matched no datums, with `enable_stats: true`, then calling `pachctl get-logs --job=$jid` hangs

```console
$ pachctl list-pipeline
NAME             INPUT                                                                                             OUTPUT                  CREATED      STATE
gf-score (gf-score-configs:/pipeline/score_config*.yml ⨯ gf-datasets:/*.gz ⨯ gf-models:/*) gf-score/master 12 hours ago standby

$ pachctl list-job -p gf-atomnet-score
ID                               OUTPUT COMMIT                                     STARTED      DURATION           RESTART PROGRESS  DL UL STATE
04d4d6292a6b42e484a92ed1b8c6359a gf-score/a43e28f664664b4e869e3754fc32a760 12 hours ago Less than a second 0       0 + 0 / 0 0B 0B success

$ pachctl -vvvv get-logs --job=04d4d6292a6b42e484a92ed1b8c6359a
[etcd/grpc] INFO  2019/01/31 10:40:19 log.go:172: INFO: 2019/01/31 10:40:19 parsed scheme: ""
[etcd/grpc] INFO  2019/01/31 10:40:19 log.go:172: INFO: 2019/01/31 10:40:19 scheme "" not registered, fallback to default scheme
[etcd/grpc] INFO  2019/01/31 10:40:19 log.go:172: INFO: 2019/01/31 10:40:19 ccResolverWrapper: sending new addresses to cc: [{pach.example.com:650 0  <nil>}]
[etcd/grpc] INFO  2019/01/31 10:40:19 log.go:172: INFO: 2019/01/31 10:40:19 ClientConn switching balancer to "pick_first"
[etcd/grpc] INFO  2019/01/31 10:40:19 log.go:172: INFO: 2019/01/31 10:40:19 pickfirstBalancer: HandleSubConnStateChange: 0xc420560410, CONNECTING
[etcd/grpc] INFO  2019/01/31 10:40:19 log.go:172: INFO: 2019/01/31 10:40:19 pickfirstBalancer: HandleSubConnStateChange: 0xc420560410, READY
```

It seems to know what's up with the pipeline in general, though:

```console
$ pachctl get-logs -p bug3059
no pods belonging to the rc "pipeline-bug3059-v1" were found
```

And, perhaps more importantly, `pachctl get-logs --raw --job=$jid` **does** return the log JSON

**What you expected to happen?**:

Not to hang

**How to reproduce it (as minimally and precisely as possible)?**:

1. ensure a repo exists, and has a folder so the top-glob will match (otherwise #3068 will bite you), but specify a non-matching child glob

   the objective is to have the pipeline be "successful" but not _do_ anything (and thus no logs in the `stats` branch)
1. `yaml2json` the following pipeline into `pachctl create-pipeline`
1. call `pachctl get-logs --job=$jid`
1. observe the hang

```yaml
pipeline:
    name: bug3059
enable_stats: true
standby: true
transform:
    image: busybox:latest
    cmd:
    - /bin/true

parallelism_spec:
  constant: 1

input:
    pfs:
        name: something
        repo: repo3
        branch: master
        glob: /exists/*/but-not-this
```

**Anything else we need to know?**:

**Environment?**:
- Kubernetes version (use `kubectl version`): `Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.3", GitCommit:"435f92c719f279a3a67808c80521ea17d5715c66", GitTreeState:"clean", BuildDate:"2018-11-26T12:46:57Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}`
- Pachyderm CLI version (use `pachctl version`): `pachctl             1.8.2` `pachd               1.8.2`
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s): AWS
- OS (e.g. from /etc/os-release): `VERSION="18.04.1 LTS (Bionic Beaver)"`
- Others:

**Comment by ysimonson** [comment]
No longer reproducible.

Tested with a pipeline spec almost identical to the above, against the opencv demo:

```yaml
pipeline:
    name: bug
enable_stats: true
standby: true
transform:
    image: busybox:latest
    cmd:
    - /bin/true

parallelism_spec:
  constant: 1

input:
    pfs:
        name: something
        repo: images
        branch: master
        glob: /*/does-not-exist
```

Running `p -vvvv logs --job=3d0017c985734464983c0ae5fb821afb` exited with 0.
