### ISSUE TITLE
Better documentation for cluster API ingress

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#3466]
It seems a lot of user questions center around how API ingress works. Didn't find docs about this, so just wrote this up for a customer. Should probably be migrated into our docs if we don't have something like this already

To clarify about ingress/`NodePort`s: pachyderm doesn't really care how a user gets access to it, so long as their local `pachctl` client can talk to the `pachd` pod. `pachctl` has built-in support for two different methods: setting the `PACHD_ADDRESS`, and using `pachctl port-forward`

1. setting the `PACHD_ADDRESS` env var to point at a `host:port` that directs traffic to the `pachd` pod tells `pachctl` to just talk to that endpoint directly. This is the flow `NodePort` supports -- it makes the internal `pachd` pod's API port accessible on the cluster's external address, so that users can set `PACHD_ADDRESS=cluster-address:30650` (`30650` is the default), and the k8s/OC cluster will send that traffic to the `pachd` pod. because this port is a global resource at the k8s/OC cluster level, it needs to be unique per pachyderm cluster. but it can be changed to whatever you want for a given pachyderm deployment, and shouldn't affect pachyderm's internal operation (so long as the user of `pachctl` has the right value in their `PACHD_ADDRESS` variable)

2. ~~`pachctl port-forward` piggy-backs on `kubectl` to fetch the name of the `pachd` pod within the k8s cluster/namespace the user is currently connected to, and then runs `kubectl port-forward` to direct traffic from the user's local machine to `pachd` via the k8s API. In this case, setting the `PACHD_ADDRESS` variable isn't needed, but the user needs to have k8s access set up, pointing at the namespace for their pachyderm cluster~~

Edited, based on @ysimonson 's suggestion:

2. `pachctl port-forward` piggy-backs off `kubectl`'s config file and client API -- it reads `kubectl`'s config file to fetch the name of the pachd pod within the k8s cluster/namespace the user is currently connected to, then uses the kubernetes API to effectively run `kubectl port-forward`. This directs traffic from the user's local machine to `pachd` via the k8s API. If using `pachctl port-forward`, then setting the `PACHD_ADDRESS` variable isn't needed. Instead, the user needs to have k8s access set up, pointing at the namespace for their pachyderm cluster

As of 1.8.3 `pachctl port-forward` happens automatically when running any `pachctl` command that tries to access `pachd`, but in order to open a persistent tunnel to a number of other ports pachyderm uses (the dashboard, git and auth hooks, the built-in HTTP file API, etc) users will still need to run `pachctl port-forward` explicitly

also, it seems pachctl port-forward isn't working with openshift, but the following `oc port-forward` command does effectively the same thing: 

```
PACHD_POD_NAME=`oc get pod --output=json | jq -r '.items[] | select(.metadata.name|startswith("pachd")).metadata.name'`  #  -r flag is needed to not get quotes in the output

oc port-forward pod/$PACHD_POD_NAME 30650:1650
```

**Comment by JoeyZwicker** [comment]
Thanks @gabrielgrant This is really helpful and we can turn into docs. 

Do we eventually want to add anything about the following in this doc?
- pach_config or kube_config file?
- Using an ELB to create a connection endpoint for users?
- Discuss support (or lackthereof) for namespaces and the nuances for each of these methods
- Discuss complications, if any, that come from running multiple pachyderm clusters -- using kubectl set-context, etc.

We'll also add a mention that port-forward can be slow for data ingestion from you local machine.

**Comment by gabrielgrant** [comment]
Yup, think we want to add info about all of those things :P

**Comment by gabrielgrant** [comment]
Also, turned out the problem of the particular customer this content was originally written for was actually a proxy issue. So we should also document that "if you're connecting with port-forward, you're using 0.0.0.0 -- make sure your proxy handles that appropriately"

**Comment by JoeyZwicker** [comment]
#2684 also has useful info

**Comment by gabrielgrant** [comment]
@ysimonson with the new auto-port-forward, I assume this will still fall back to using `localhost:30650` if no k8s config is found, meaning if you want to set up some other sort of tunnel, that's where you should be binding it?

pretty sure that's the case, since that's what we're doing with openshift: 
```
PACHD_POD_NAME=`oc get pod --output=json | jq -r '.items[] | select(.metadata.name|startswith("pachd")).metadata.name'`  #  -r flag is needed to not get quotes in the output

oc port-forward pod/$PACHD_POD_NAME 30650:1650```

**Comment by ysimonson** [comment]
@gabrielgrant correct

**Comment by ysimonson** [comment]
Because port forwarding reads the default k8s config, and microk8s does not put its config in the default location, microk8s users who do not want to set `PACHD_ADDRESS` will need to do the following: https://github.com/pachyderm/pachyderm/issues/3290#issuecomment-461632187

**Comment by ysimonson** [comment]
As 1.8.4, users who want to disable implicit port forwarding can run any command with `--no-port-forwarding`

**Comment by gabrielgrant** [comment]
@ysimonson that seems kinda annoying if you want to always use some other tunneling method. did we come to a conclusion on having an env var/config setting for this?

**Comment by ysimonson** [comment]
Other tunneling methods should be handled by setting `PACHD_ADDRESS`, right?

**Comment by gabrielgrant** [comment]
yes, i think so. we may want to revisit the global config vs local config vs envvar question at some point, but that's outside the scope of this issue

**Comment by gabrielgrant** [comment]
Seems there's a bunch of relevant info here: http://docs.pachyderm.io/en/latest/deployment/amazon_web_services/connecting_to_your_cluster.html

(some of which is actually directly related to AWS deployments, but much of which is not)

**Comment by jrvanalstine** [comment]
I'm attempting to put pachd behind an ambassador/envoy api-gateway with the rest of our services. It doesn't seem like I can really use pachd as a NodePort service here. So i'm attempting to have pachd just be type: ClusterIP and have envoy forward foo.bar.com/pachd/ to pachd port 650.

Here's the pachd service with ambassador annotation:
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      name: pachd-dev-mapping
      prefix: /pachd/
      host: foo.bar.com
      service: pachd.pachyderm-dev:650
    prometheus.io/port: "9091"
    prometheus.io/scrape: "true"
  creationTimestamp: null
  labels:
    app: pachd
    suite: pachyderm
  name: pachd
  namespace: pachyderm-dev
spec:
  ports:
  - name: api-grpc-port
    port: 650
    targetPort: 0
  - name: trace-port
    port: 651
    targetPort: 0
  - name: api-http-port
    port: 652
    targetPort: 0
  - name: saml-port
    port: 654
    targetPort: 0
  - name: api-git-port
    port: 999
    targetPort: 0
  selector:
    app: pachd
  type: ClusterIP
status:
  loadBalancer: {}
```

I have not quite set this up correctly because when I curl -v https://foo.bar.com/pachd/ I get back:
```
*   Trying ip.blah.blah.blah...
* TCP_NODELAY set
* Connected to foo.bar.com (ip.blah.blah.blah) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: CN=foo.bar.com
*  start date: Mar  4 00:00:00 2019 GMT
*  expire date: Apr  4 12:00:00 2020 GMT
*  subjectAltName: host "foo.bar.com" matched cert's "foo.bar.com"
*  issuer: C=US; O=Amazon; OU=Server CA 1B; CN=Amazon
*  SSL certificate verify ok.
> GET /pachd/ HTTP/1.1
> Host: foo.bar.com
> User-Agent: curl/7.58.0
> Accept: */*
> 
< HTTP/1.1 503 Service Unavailable
< content-length: 57
< content-type: text/plain
< date: Thu, 07 Mar 2019 01:21:46 GMT
< server: envoy
< 
* Connection #0 to host foo.bar.com left intact
upstream connect error or disconnect/reset before headers
```

You can see the ambassador loadbalancer settings here:
```
apiVersion: v1
kind: Service
metadata:
  labels:
    service: ambassador
  name: ambassador
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "[MY CERT ARN]"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind:  Module
      name:  ambassador
      config:
        use_remote_address: true
        use_proxy_proto: true
      ---
      apiVersion: ambassador/v1
      kind: Module
      name: tls
      config:
        server:
          enabled: true
          redirect_cleartext_from: 80
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    service: ambassador

```

I am not totally sure why i'm getting the 503 back, but I figured i'd post this in case someone sees something obviously wrong.
