### ISSUE TITLE
Connecting to pachd via Ambassador/Envoy api-gateway example

### ISSUE THREAD

**Issue by jrvanalstine** [pachyderm/pachyderm#3555]
Goal: Put pachd behind Ambassador API-gateway and access via PACHD_ADDRESS.

Let foo.bar.com be the address of the ambassador service. Here's the manifest of the ambassador service deployed on aws:
```
apiVersion: v1
kind: Service
metadata:
  labels:
    service: ambassador
  name: ambassador
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "[CERTIFICATE ARN]"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind:  Module
      name:  ambassador
      config:
        use_remote_address: true
        use_proxy_proto: true
      ---
      apiVersion: ambassador/v1
      kind: Module
      name: tls
      config:
        server:
          enabled: true
          redirect_cleartext_from: 80
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    service: ambassador

```
Here's the [mapping](https://www.getambassador.io/reference/mappings/) on the pachd service. Notice the service type is changed from NodePort to ClusterIP: 
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      name: pachd-dev-mapping
      grpc: True
      prefix: /pachd/dev/
      host: foo.bar.com
      service: pachd.pachyderm-dev:650
    prometheus.io/port: "9091"
    prometheus.io/scrape: "true"
  creationTimestamp: null
  labels:
    app: pachd
    suite: pachyderm
  name: pachd
  namespace: pachyderm-dev
spec:
  ports:
  - name: api-grpc-port
    port: 650
    targetPort: 0
  - name: trace-port
    port: 651
    targetPort: 0
  - name: api-http-port
    port: 652
    targetPort: 0
  - name: saml-port
    port: 654
    targetPort: 0
  - name: api-git-port
    port: 999
    targetPort: 0
  selector:
    app: pachd
  type: ClusterIP
status:
  loadBalancer: {}
```
The grpc: True annotation corrects the error [here](https://github.com/pachyderm/pachyderm/issues/3466#issuecomment-470347342). 

I can successfully curl https://foo.bar.com/pachd/dev/ , but I am having difficulties getting the client settings correct. I have set PACHD_ADDRESS=https://foo.bar.com/pachd/dev/, but the client complains about a missing port. How should I configure the client and PACHD_ADDRESS now?
