### ISSUE TITLE
Cannot Access Jupyter Service running on an EKS cluster in AWS

### ISSUE THREAD

**Issue by rp4fx12** [pachyderm/pachyderm#3801]
**What happened?**:
We launched a pipeline following this tutorial - https://docs.pachyderm.io/en/v1.8.5/fundamentals/creating_services.html. We then created a kubernetes ingress to expose the service to our local machines. However, we were unable to access the jupyter pipeline from our local machines. In addition, we tried to curl {service_cluster_Ip}:30888 from a container in the same namespace as the jupyter pipeline pods but got a connection refused response (we tried other ports just for kicks but those hang - I'm guessing this means the service is configured correctly?). We have also tested out the aws networking setttings (security groups, subnets) with other apis and they work.

Sample pipeline
```
{
  "pipeline": {
      "name": "jup"
    },
  "input": {
      "pfs": {
          "glob": "/",
          "repo": "mtd-group"
      }
  },
  "service": {
      "external_port": 30888,
      "internal_port": 3000
  },
  "transform": {
      "cmd":
        ["jupyter", "notebook", "--ip", "0.0.0.0", "--port", "3000", "--NotebookApp.token={some_token}", "--Appmode.show_edit_button=False",  "--Appmode.show_other_buttons=False"],
        "image": "{internal_docker_registry}/public/jupyter-alpine:1.5.3"
  }
}
```
Sample Ingress:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/certificate-arn: {cert}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/security-groups: {sgs}
    alb.ingress.kubernetes.io/subnets: {subnets}
    alb.ingress.kubernetes.io/success-codes: 200,302
    alb.ingress.kubernetes.io/tags: Cluster={cluster-name},Service=pipeline-jup-v1-user
    kubernetes.io/ingress.class: alb
  generation: 2
  labels:
    app: pipeline-jup-v1-user
  name: pipeline-jup-v1-user
  namespace: {namespace}
spec:
  rules:
  - host: {url}
    http:
      paths:
      - backend:
          serviceName: pipeline-jup-v1-user
          servicePort: 30888
        path: /*
```

**What you expected to happen?**:

We expected to hit the {url} in the host block in the ingress manifest (from a browser) and access our service.

**How to reproduce it (as minimally and precisely as possible)?**:

Run the above pipeline and run the ingress on an eks cluster and see if you can access the jupyter ui. You may need security groups, subnets and a cert.

**Anything else we need to know?**:

We did not see any exposed container ports on the pipeline pod when we looked at its manifest.

**Environment?**:
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-03-01T23:34:27Z", GoVersion:"go1.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.8-eks-7c34c0", GitCommit:"7c34c0d2f2d0f11f397d55a46945193a0e22d8f3", GitTreeState:"clean", BuildDate:"2019-03-01T22:49:39Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

- Pachyderm CLI version (use `pachctl version`):

```
COMPONENT           VERSION
pachctl             1.8.7
pachd               1.8.7
```
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):

 aws - eks

- OS (e.g. from /etc/os-release):

AmazonLinux2

- Others:
