### ISSUE TITLE
add liveness probe to etcd deployment

### ISSUE THREAD

**Issue by brokenjacobs** [pachyderm/pachyderm#3803]
**What is the goal / desired outcome?**
the current etcd deployment for pachyderm doesn't have a liveness probe

**If there is a way to accomplish this today via workaround, what does that require?**
you can add one manually

**(Optional) What is your proposal for a feature to solve this?**
have the spec for the etcd pod include:
```
      livenessProbe:
          exec:
            command:
            - /bin/sh
            - -ec
            - ETCDCTL_API=3 etcdctl --endpoints=http://[127.0.0.1]:2379 endpoint health
          failureThreshold: 0
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 15
```
