### ISSUE TITLE
Add support for prometheus monitoring of etcd

### ISSUE THREAD

**Issue by brokenjacobs** [pachyderm/pachyderm#3805]
**What is the goal / desired outcome?**
currently the etcd deployment pachyderm creates is not exporting any metrics to prometheus.

**If there is a way to accomplish this today via workaround, what does that require?**
In the template for etcd, add the following to the command line for etcd:
```--listen-metrics-urls=http://0.0.0.0:9091```

Then in the metadata add the following annotations so the prometheus operator can pick it up:
```
    metadata:
      annotations:
        prometheus.io/port: '9091'
        prometheus.io/scrape: 'true'
```

This is preferable to scraping the built in endpoint, as this will continue to work even if mTLS is enabled for etcd authentication
