### ISSUE TITLE
Prometheus operator annotations are in the wrong place in the deployment yaml

### ISSUE THREAD

**Issue by brokenjacobs** [pachyderm/pachyderm#3806]
**What happened?**:
Prometheus doesn't scrape Pachd for metrics
**What you expected to happen?**:
metrics collection of pachd
**How to reproduce it (as minimally and precisely as possible)?**:
Deploy with the pachctl command
**Anything else we need to know?**:
The prometheus operator annotations are currently being added to the pachd service, which is not correct. They need to be added to the pachd container. Under the deployment template add the following annotations:
```
    metadata:
      annotations:
        prometheus.io/port: '9091'
        prometheus.io/scrape: 'true'
```

**Comment by jdoliner** [comment]
Spent some time looking at this. I'm having trouble finding a conclusive answer that states it's wrong to put prometheus annotations on the service. I'm seeing docs that references putting annotations on pods and on services. In addition I tried deploying prometheus and checking to see if I could see pachd metrics and found that I could, this is in a cluster that has a prometheus annotation on the service but not the pod. This would not be hard to change so we're not opposed to doing it. It would be good to have a bit better understanding of what the rules are here though. Do you have an docs you found about why putting annotations on the service is incorrect? Nothing I found seemed canonical to me. In addition I'm wondering why my prometheus is able to scrape pachd with only service annotations, it's possible that it's just scraping everything and that's why it works.

**Comment by brokenjacobs** [comment]
It is perfectly legitimate to put the annotation on the service. However if you do this, you must also expose the Prometheus monitoring port on the service, which is not currently being done.

Additionally this will only pull metrics from whatever pod backs the service, not all pods.

Also final note, ServiceMonitor CRD support for the Prometheus operator seems to be where all this is moving towards, and away from the annotations. And to your point, servicemonitors monitor services not pods, so it seems annotations on the service is the more appropriate place to put them, just make sure to map the port for the metrics.

**Comment by brokenjacobs** [comment]
Technically they qualify pods to monitor via services... but the point is still valid I think.

**Comment by brokenjacobs** [comment]
I went and double checked the manifest for pachd's service:
```yaml
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "9091"
    prometheus.io/scrape: "true"
  creationTimestamp: null
  labels:
    app: pachd
    suite: pachyderm
  name: pachd
  namespace: pachyderm
spec:
  ports:
  - name: api-grpc-port
    nodePort: 30650
    port: 650
    targetPort: 0
  - name: trace-port
    nodePort: 30651
    port: 651
    targetPort: 0
  - name: api-http-port
    nodePort: 30652
    port: 652
    targetPort: 0
  - name: saml-port
    nodePort: 30654
    port: 654
    targetPort: 0
  - name: api-git-port
    nodePort: 30999
    port: 999
    targetPort: 0
  - name: s3gateway-port
    nodePort: 30600
    port: 600
    targetPort: 0
  selector:
    app: pachd
  type: NodePort
status:
  loadBalancer: {}
```

Port 9091 is not in the spec.ports.

When I tried this using scrape annotations it didn't work. Recently I had another service I was building a ServiceMonitor for using the Prometheus operator, and it would not pick up the metrics endpoint until I added the port to the spec.ports section of the service. So I think this is expected, it won't pick it up unless it's in the spec.

**Comment by brokenjacobs** [comment]
I would recommend revising as follows:
```yaml
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "9091"
    prometheus.io/scrape: "true"
  creationTimestamp: null
  labels:
    app: pachd
    suite: pachyderm
  name: pachd
  namespace: pachyderm
spec:
  ports:
  - name: api-grpc-port
    nodePort: 30650
    port: 650
    targetPort: 0
  - name: trace-port
    nodePort: 30651
    port: 651
    targetPort: 0
  - name: api-http-port
    nodePort: 30652
    port: 652
    targetPort: 0
  - name: saml-port
    nodePort: 30654
    port: 654
    targetPort: 0
  - name: api-git-port
    nodePort: 30999
    port: 999
    targetPort: 0
  - name: s3gateway-port
    nodePort: 30600
    port: 600
    targetPort: 0
  - name: prometheus
    port: 8081
    targetPort: 8081
  selector:
    app: pachd
  type: NodePort
status:
  loadBalancer: {}
---
# Partial deployment spec for pachd
kind: Deployment
metadata:
  name: pachd
spec:
  template:
    spec:
      containers:        
        name: pachd
        ports:
        - containerPort: 650
          name: api-grpc-port
          protocol: TCP
        - containerPort: 651
          name: trace-port
        - containerPort: 652
          name: api-http-port
          protocol: TCP
        - containerPort: 653
          name: peer-port
          protocol: TCP
        - containerPort: 999
          name: api-git-port
          protocol: TCP
        - containerPort: 654
          name: saml-port
          protocol: TCP
        # ADD THIS FOR PROMETHEUS
        - containerPort: 9091
          name: prometheus
          protocol: TCP
```
