### ISSUE TITLE
does "egress" configuration for pipeline means that putting files into /pfs/out will not consume disk space?

### ISSUE THREAD

**Issue by aka-toxa** [pachyderm/pachyderm#4247]
Hi 

I have this question because it's not super clear from the documentation.

The documentation said that 

```
egress enables you to push the results of a pipeline to an external datastore such as Amazon S3, Google Cloud Storage, or Azure Blob Storage
```

Does that mean that all files from output directory will live only on specified store and not on the disk attached to the pod?

I wonder because I have a case where I built a data processing pipeline that lives forever and waits until new files arrived in the input repo, I have hundreds of thousands of files that should be processed by this pipeline one by one and I wonder how can I delete processed files to not consume node's disk with old, already processed files. I've already managed to configure lazy input to not consume disk space by input files and now I faced with the issue where pachyderm folder grows because of the output folder

**Comment by aka-toxa** [comment]
it's on azure

hmm maybe I deployed things wrong because it eats disk attached to the pod that apparently is a node disk

**Comment by JoeyZwicker** [comment]
Did you do `pachctl deploy azure` or `deploy local` to an azure instance?

**Comment by aka-toxa** [comment]
I did 

```
helm upgrade pachyderm stable/pachyderm --tls --version 0.1.7 --install --wait --recreate-pods --reset-values --namespace pachyderm -f <(envsubst < $(dirname $BASH_SOURCE)/pachydermConfig.yaml)
```

where pachydermConfig.yaml is

```
rbac:
  create: true
credentials: "microsoft"
microsoft:
  container: "" # Blob Container name
  id: "" # Storage account name
  secret: "" # Storage account access key
pachd:
  replicaCount: 1
  pfsCache: 4G
  resources:
    requests:
      cpu: 1000m
      memory: 2G
etcd:
  persistence:
    storageClass: managed-premium
    enabled: true
    size: 10G
    accessMode: ReadWriteOnce
  resources:
    requests:
      cpu: 1000m
      memory: 2G
```

did you mean that `pfs/out` folder is mounted from the azure blob, not from disk? it's strange, because when I give 100TB of data to pachyderm it shutdown the cluster because it eats whole disk.
