### ISSUE TITLE
pod_spec is broken

### ISSUE THREAD

**Issue by suneeta-mall** [pachyderm/pachyderm#4286]
On pach 1.9.8, applying following pipeline spec, gives me `parse error while canonicalizing CreatePipelineRequest: json: cannot unmarshal object into Go value of type string`

```
input:
  pfs:
    glob: "/"
    repo: x
pipeline:
  name: y
transform:
  cmd:
  - "/bin/bash"
  image: blah
  stdin:
  - "blah"
datum_tries: 2
pod_spec:
  serviceAccount: "ml-user"
  serviceAccountName: "ml-user"
```
