### ISSUE TITLE
clearly document prometheus metrics and setup

### ISSUE THREAD

**Issue by pappasilenus** [pachyderm/pachyderm#4546]
** Describe the issue that needs documentation **

We should clearly document what metrics we provide to prometheus and what they measure.  Attached is a summary from the source.

[promethus-metrics.txt](https://github.com/pachyderm/pachyderm/files/4136060/promethus-metrics.txt)

**Anything else we need to know?**

Unclear if we should talk about setting it up; I think that's a separate issue

**Environment:**
- Kubernetes version (use `kubectl version`):
- Pachyderm CLI and pachd server version (use `pachctl version`):
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
- OS:
- Other:

**Comment by mindthevirt** [comment]
Setup with Prometheus helm chart:

1. Install the Prometheus helm chart.
2. Create a ServiceMonitor for Pachyderm in Kubernetes with:

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: pachyderm-scraper
  labels:
    suite: pachyderm
spec:
  selector:
    matchLabels:
      suite: pachyderm
  endpoints:
  - port: prometheus-metrics
```

^ tells Prometheus what targets to scrape. In this case it is looking for anything with the label `suite: pachyderm`, which is by default associated with all Pachyderm resources and scrape the `prometheus-metrics` port which is specified within the service for all Pachyderm pipelines.

Once the ServiceMonitor has been created, you can browse to your prometheus server and click on targets (HTTP://prometheus-ip/targets). The `pachyderm-scraper` should show up. Example is shown below:

![image](https://user-images.githubusercontent.com/23178090/103497027-3889dd80-4e0e-11eb-9d70-eb8448c9dd89.png)

If everything looks correct, you should be able to see the new metrics:

![image](https://user-images.githubusercontent.com/23178090/103497055-56efd900-4e0e-11eb-9c0e-097a90e3c16a.png)
