### ISSUE TITLE
HostPath to docker socket should not be a default

### ISSUE THREAD

**Issue by marcadella** [pachyderm/pachyderm#4575]
Pachyderm create `rc`s with a HostPath to docker.sock:

```
docker:
  Type: HostPath
  Path: /var/run/docker.sock
  HostPathType:
```

HostPath mounts are forbidden in most cases, so could this be made optional? In addition, since #2813 workers do not need to have access to docker anyway. I removed the HostPath and my pipelines work just fine.

**Environment?**:
- Pachyderm 1.9.11
