### ISSUE TITLE
Flexible trigger pipeline for KF pipelines

### ISSUE THREAD

**Issue by msteffen** [pachyderm/pachyderm#5021]
## Objective
Have a pipeline spec that users can just copy+edit+use to run KF pipelines from Pachyderm. We started implementing this in our first pass the KF demo, and we ought to come back and finish it.

## Usage
The idea is that the pipeline spec looks something like:
```
pipeline:
  name: trigger-kubeflow
transform:
  image: pachyderm/kubeflow_demo_trigger@${KUBEFLOW_DEMO_TRIGGER_HASH}
  cmd: [ /bin/trigger.sh ]
  env:
    # KF_PIPELINE_NAME is set in the UI when you create the pipeline. The value
    # in pipeline.py is not used AFAICT. Alternatively, if you create the pipeline via the
    # KFP API, this is the 'pipeline_name' field.
    KF_PIPELINE_NAME: "mnist_pipeline"

    # Pipeline parameter that sets your pipeline's S3 endpoint (users must add this to
    # their pipelines themselves)
    S3_ENDPOINT_PARAM_NAME: "s3_endpoint" # s3_endpoint is the default--optional

    # The namespace where kubeflow is deployed, so pach can call the KFP API and
    # create runs
    KUBEFLOW_NAMESPACE: "kubeflow" # "kubeflow" is the default--optional

    # Env vars that start with "KF_PARAM_" are passed to the pipeline as
    # parameters
    KF_PARAM_input_bucket: "input"
s3_out: true  # Must be set
input:
  # Users specify their inputs here. It should always be a cross of some number of S3 inputs,
  # as this trigger pipeline will not read anything from the `/pfs` directory that has been exposed
  # to it directly
  pfs:
    name: input      # Name of the input bucket
    repo: input-repo # Pachyderm repo accessed via this bucket
    glob: /          # Must be exactly this
    s3: true         # Must be set
EOF
```
