### ISSUE TITLE
Pachyderm Service port mapping isn't working

### ISSUE THREAD

**Issue by JimmyWhitaker** [pachyderm/pachyderm#5135]
**What happened?**: Pachyderm Services seem to be broken. When creating a service, the server is not accessible on the designated port. When inspecting the k8s services, I see the pipeline, but it appears to be mapping the incorrect port: 
```
service/pipeline-jupyter-v1        ClusterIP      10.100.72.188    <none>        80/TCP,9090/TCP                                                                                     78s
service/pipeline-jupyter-v1-user   NodePort       10.104.215.4     <none>        30887:30887/TCP
```

**What you expected to happen?**: The service should be served on the `external_port` defined. 

**How to reproduce it (as minimally and precisely as possible)?**:

Pipeline: jupyter.json
```json
{
    "pipeline":{
        "name":"jupyter"
    },
    "input": {
        "pfs": {
            "glob": "/",
            "repo": "input"
        }
    },
    "service": {
        "external_port": 30887,
        "internal_port": 8888
    },
    "transform": {
        "cmd": [
            "start-notebook.sh"
        ],
        "image": "jupyter/datascience-notebook"
    }
}
```
File: example.txt
```txt
hello world
```

Commands to reproduce: 
```
pachctl create repo input
pachctl create pipeline -f jupyter.json
pachctl put file input@master -f example.txt
pachctl log --pipeline=jupyter   # no output
pachctl logs --pipeline=jupyter --raw   # no output
kubectl get all
```

**Anything else we need to know?**:

**Environment?**:
- Kubernetes version (use `kubectl version`): 
```
minikube version: v1.9.2
commit: 93af9c1e43cab9618e301bc9fa720c63d5efa393

Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T23:35:15Z", GoVersion:"go1.14.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:50:46Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```
- Pachyderm CLI and pachd server version (use `pachctl version`):
```
COMPONENT           VERSION
pachctl             1.11.0
pachd               1.11.0
```
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s): local minikube
- OS (e.g. from /etc/os-release): macOS Catalina 10.15.5
- Others:

**Comment by brendoncarroll** [comment]
This appears to be cosmetic.  I am able to curl the server at the minikube IP and the external port.

According to the documentation here https://kubernetes.io/docs/concepts/services-networking/service/
TargetPort is set to the same as Port.
```yaml
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: NodePort
  selector:
    app: MyApp
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 80
      targetPort: 80
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30007
```
I will have a fix up shortly.
