### ISSUE TITLE
prometheus-metrics needs to be added for pachd - /spec/ports/

### ISSUE THREAD

**Issue by mindthevirt** [pachyderm/pachyderm#5598]
**What happened?**:
When using the prometheus-community helm chart, pachd metrics are not being displayed since annotations are no longer support and instead a port "prometheus-metrics" has to be exposed on the pachd service.

**What you expected to happen?**:
Pachd metrics should show in prometheus.

**How to reproduce it (as minimally and precisely as possible)?**:
1. helm install prometheus stable/prometheus-operator
2. Create a ServiceMonitor looking to scrape metrics from `suite: pachyderm`

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: pachyderm-scraper
  labels:
    suite: pachyderm
spec:
  selector:
    matchLabels:
      suite: pachyderm
  endpoints:
  - port: prometheus-metrics
```
3. Check if Prometheus has the pachd metrics available - they will not be available
4. To fix it, add the following to pachd service:

```
  - name: prometheus-metrics
    nodePort: 30656
    port: 656
    protocol: TCP
    targetPort: 656

```
**Anything else we need to know?**:
One of the most common ways to deploy prometheus currently is via the prometheus-community helm chart: https://github.com/prometheus-community/helm-charts

**Environment?**:
- Kubernetes version (use `kubectl version`): 1.19
- Pachyderm CLI and pachd server version (use `pachctl version`): 1.12
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s): docker desktop with k8s
- OS (e.g. from /etc/os-release): OSX
- Others:
