### ISSUE TITLE
Service pipeline does not expose ports correctly

### ISSUE THREAD

**Issue by mindthevirt** [pachyderm/pachyderm#5606]
**What happened?**:
When specifying a service pipeline with the following port configuration:
```
"service": {
        "external_port": 30888,
        "internal_port": 8888
    },
```
the service for the pipeline sets the port mapping incorrectly to:
```
  ports:
  - name: user-port
    nodePort: 30801
    port: 30801
    protocol: TCP
    targetPort: 8888
```

**What you expected to happen?**:
The service for the pipeline should set the port = targetPort as shown below, otherwise, the routing of the traffic is not working:

```
  ports:
  - name: user-port
    nodePort: 30801
    port: 8888
    protocol: TCP
    targetPort: 8888
```

**How to reproduce it (as minimally and precisely as possible)?**:
Create any service pipeline.

**Environment?**:
- Kubernetes version (use `kubectl version`): 1.19
- Pachyderm CLI and pachd server version (use `pachctl version`): 1.12/1.12
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s): aws/minikube/docker desktop
