### ISSUE TITLE
CreatePipeline fails but the pipeline is created

### ISSUE THREAD

**Issue by GuiGav** [pachyderm/pachyderm#5721]
What happened?:

I encounter errors when calling APIClient.CreatePipeline but the pipeline is successfully created 

I tried to use a retry function to see if the creation error would happen every times but then I saw that the first creation actually worked
```
All attempts fail:
#1: could not create/update stats branch: rpc error: code = Unknown desc = etcdserver: mvcc: required revision is a future revision
#2: pipeline 7b6cc05b-d520-4022-bd88-2c5f760b8862-p already exists
#3: pipeline 7b6cc05b-d520-4022-bd88-2c5f760b8862-p already exists
#4: pipeline 7b6cc05b-d520-4022-bd88-2c5f760b8862-p already exists
```

What you expected to happen?:

I expect that when the creation failed, no pipeline is created

How to reproduce it (as minimally and precisely as possible)?:

It happens randomly, but I started encountering the ` rpc error: code = Unknown desc = etcdserver: mvcc: required revision is a future revision` error after changing etcd deployment to a statefulset with 3 replicas (this decreased cpu and ram consumption when performing lots of read on pachyderm) 

Anything else we need to know?:

Environment?:

    Kubernetes version (use kubectl version): 1.17
    Pachyderm CLI and pachd server version (use pachctl version): 1.11.8
    Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s): aws
    OS (e.g. from /etc/os-release):
    Others:

Thanks a lot for your help !

**Comment by echohack** [comment]
Hey @GuiGav thanks for opening this issue!

I want to check with our engineering team, but this seems like it (could be?) an [etcd auto compaction issue](https://etcd.io/docs/v3.4.0/op-guide/maintenance/) or an issue with disk space. Can you share what your etcd container settings are? I'm also interested in the json you have for your `statefulset`, particularly disk space of the volume claim.


For example, for a local deployment, you might have something like this in a `deployment.json`

```json
          {
            "name": "etcd",
            "image": "pachyderm/etcd:v3.3.5",
            "command": [
              "/usr/local/bin/etcd",
              "--listen-client-urls=http://0.0.0.0:2379",
              "--advertise-client-urls=http://0.0.0.0:2379",
              "--data-dir=/var/data/etcd",
              "--auto-compaction-retention=1",
              "--max-txn-ops=10000",
              "--max-request-bytes=1000000",
              "--quota-backend-bytes=8589934592"
            ],
            "ports": [
              {
                "name": "client-port",
                "containerPort": 2379
              },
              {
                "name": "peer-port",
                "containerPort": 2380
              }
            ],
            "resources": {
              "limits": {
                "cpu": "250m",
                "memory": "4096M"
              },
              "requests": {
                "cpu": "250m",
                "memory": "4096M"
              }
            },
 ```

**Comment by echohack** [comment]
Hi @GuiGav After a discussion with engineering, we have a few more ideas about what this could be. Can we get a few more things?

- `pachd` logs from when you run `CreatePipeline` and hit the error.
- the deployment spec for your cluster, especially the etcd cluster

**Comment by GuiGav** [comment]
Hi @echohack , here are my deployment configs : 

```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: etcd
    suite: pachyderm
  name: etcd
  namespace: pachyderm
spec:
  replicas: 3
  selector:
    matchLabels:
      app: etcd
      suite: pachyderm
  serviceName: etcd-headless
  template:
    metadata:
      labels:
        app: etcd
        suite: pachyderm
      name: etcd
      namespace: pachyderm
      annotations:
        sidecar.istio.io/proxyMemoryLimit: "1024Mi"
        sidecar.istio.io/proxyCPULimit: "1000m"
    spec:
      containers:
      - args:
        - '"/usr/local/bin/etcd" "--listen-client-urls=http://0.0.0.0:2379" "--advertise-client-urls=http://0.0.0.0:2379"
          "--data-dir=/var/data/etcd" "--auto-compaction-retention=1" "--max-txn-ops=10000"
          "--max-request-bytes=52428800" "--quota-backend-bytes=8589934592" "--listen-peer-urls=http://0.0.0.0:2380"
          "--initial-cluster-token=pach-cluster" "--initial-advertise-peer-urls=http://${ETCD_NAME}.etcd-headless.${NAMESPACE}.svc.cluster.local:2380"
          "--initial-cluster=etcd-0=http://etcd-0.etcd-headless.${NAMESPACE}.svc.cluster.local:2380,etcd-1=http://etcd-1.etcd-headless.${NAMESPACE}.svc.cluster.local:2380,etcd-2=http://etcd-2.etcd-headless.${NAMESPACE}.svc.cluster.local:2380"'
        command:
        - /bin/sh
        - -c
        env:
        - name: ETCD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: pachyderm/etcd:v3.3.5
        imagePullPolicy: IfNotPresent
        name: etcd
        ports:
        - containerPort: 2379
          name: client-port
        - containerPort: 2380
          name: peer-port
        resources:
          requests:
            cpu: "1"
            memory: 2G
        volumeMounts:
        - mountPath: /var/data/etcd
          name: etcd-storage
      imagePullSecrets: null
  volumeClaimTemplates:
  - metadata:
      annotations:
        volume.beta.kubernetes.io/storage-class: etcd-storage-class
      labels:
        app: etcd
        suite: pachyderm
      name: etcd-storage
      namespace: pachyderm
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 100Gi
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: etcd
    suite: pachyderm
  name: etcd
  namespace: pachyderm
spec:
  ports:
  - name: client-port
    port: 2379
    targetPort: 0
  selector:
    app: etcd
  type: NodePort
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: pachd
    suite: pachyderm
  name: pachd
  namespace: pachyderm
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pachd
      suite: pachyderm
  strategy: {}
  template:
    metadata:
      annotations:
        sidecar.istio.io/proxyMemoryLimit: "1024Mi"
        sidecar.istio.io/proxyCPULimit: "1000m"
        iam.amazonaws.com/role: ""
      creationTimestamp: null
      labels:
        app: pachd
        suite: pachyderm
      name: pachd
      namespace: pachyderm
    spec:
      containers:
      - command:
        - /pachd
        env:
...
        readinessProbe:
          exec:
            command:
            - /pachd
            - --readiness
        resources:
          limits:
            cpu: 2000m
            memory: 1024M
          requests:
            cpu: 250m
            memory: 512M
        volumeMounts:
        - mountPath: /pach
          name: pach-disk
        - mountPath: /pachyderm-storage-secret
          name: pachyderm-storage-secret
      serviceAccountName: pachyderm
      volumes:
      - hostPath:
          path: /var/pachyderm/pachd
          type: DirectoryOrCreate
        name: pach-disk
      - name: pachyderm-storage-secret
        secret:
          secretName: pachyderm-storage-secret
status: {}

```

I'll reproduce the issue and will attach logs in a next message
