### ISSUE TITLE
pachctl delete pipeline --split-txn doesn't work with distributed etcd

### ISSUE THREAD

**Issue by GuiGav** [pachyderm/pachyderm#5944]
**What happened?**:

I ran the following 
```bash
pachctl delete pipeline 2781a826-8185-42a6-bb04-085afe7d8310-p
etcdserver: too many operations in txn request (10052 comparisons, 1840 writes: hint: set --max-txn-ops on the ETCD cluster to at least the largest of those values)
```
and then 
```
pachctl delete pipeline 2781a826-8185-42a6-bb04-085afe7d8310-p --split-txn
WARNING: If using the --split-txn flag, this command must run until complete. If a failure or incomplete run occurs, then Pachyderm will be left in an inconsistent state. To resolve an inconsistent state, rerun this command.
Are you sure you want to do this? (y/n): y
etcdserver: mvcc: required revision is a future revision
```
which leads me to this situation : 
```
pachctl list file 2781a826-8185-42a6-bb04-085afe7d8310-p@master
/pachyderm_pfs/branches/2781a826-8185-42a6-bb04-085afe7d8310-p/ master not found
```

**What you expected to happen?**:
I expected the deletion to work

**How to reproduce it (as minimally and precisely as possible)?**:
You need a pipeline with a lot of commits so deleting it exceed the maximum transaction limit. 
My deployement config is as follow, the important point is that etcd runs as a statefulset with 3 replicas : 
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: etcd
    suite: pachyderm
  name: etcd
  namespace: pachyderm
spec:
  replicas: 3
  selector:
    matchLabels:
      app: etcd
      suite: pachyderm
  serviceName: etcd-headless
  template:
    metadata:
      labels:
        app: etcd
        suite: pachyderm
      name: etcd
      namespace: pachyderm
      annotations:
        sidecar.istio.io/proxyMemoryLimit: "1024Mi"
        sidecar.istio.io/proxyCPULimit: "1000m"
    spec:
      containers:
      - args:
        - '"/usr/local/bin/etcd" "--listen-client-urls=http://0.0.0.0:2379" "--advertise-client-urls=http://0.0.0.0:2379"
          "--data-dir=/var/data/etcd" "--auto-compaction-retention=1" "--max-txn-ops=10000"
          "--max-request-bytes=10000" "--quota-backend-bytes=8589934592" "--listen-peer-urls=http://0.0.0.0:2380"
          "--initial-cluster-token=pach-cluster" "--initial-advertise-peer-urls=http://${ETCD_NAME}.etcd-headless.${NAMESPACE}.svc.cluster.local:2380"
          "--initial-cluster=etcd-0=http://etcd-0.etcd-headless.${NAMESPACE}.svc.cluster.local:2380,etcd-1=http://etcd-1.etcd-headless.${NAMESPACE}.svc.cluster.local:2380,etcd-2=http://etcd-2.etcd-headless.${NAMESPACE}.svc.cluster.local:2380"'
        command:
        - /bin/sh
        - -c
        env:
        - name: ETCD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: pachyderm/etcd:v3.3.5
        imagePullPolicy: IfNotPresent
        name: etcd
        ports:
        - containerPort: 2379
          name: client-port
        - containerPort: 2380
          name: peer-port
        resources:
          requests:
            cpu: "1"
            memory: 2G
        volumeMounts:
        - mountPath: /var/data/etcd
          name: etcd-storage
      imagePullSecrets: null
  volumeClaimTemplates:
  - metadata:
      annotations:
        volume.beta.kubernetes.io/storage-class: etcd-storage-class
      labels:
        app: etcd
        suite: pachyderm
      name: etcd-storage
      namespace: pachyderm
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 100Gi
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: etcd
    suite: pachyderm
  name: etcd
  namespace: pachyderm
spec:
  ports:
  - name: client-port
    port: 2379
    targetPort: 0
  selector:
    app: etcd
  type: NodePort
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: pachd
    suite: pachyderm
  name: pachd
  namespace: pachyderm
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pachd
      suite: pachyderm
  strategy: {}
  template:
    metadata:
      annotations:
        sidecar.istio.io/proxyMemoryLimit: "1024Mi"
        sidecar.istio.io/proxyCPULimit: "1000m"
        iam.amazonaws.com/role: ""
      creationTimestamp: null
      labels:
        app: pachd
        suite: pachyderm
      name: pachd
      namespace: pachyderm
    spec:
      containers:
      - command:
        - /pachd
        env:
...
        readinessProbe:
          exec:
            command:
            - /pachd
            - --readiness
        resources:
          limits:
            cpu: 2000m
            memory: 1024M
          requests:
            cpu: 250m
            memory: 512M
        volumeMounts:
        - mountPath: /pach
          name: pach-disk
        - mountPath: /pachyderm-storage-secret
          name: pachyderm-storage-secret
      serviceAccountName: pachyderm
      volumes:
      - hostPath:
          path: /var/pachyderm/pachd
          type: DirectoryOrCreate
        name: pach-disk
      - name: pachyderm-storage-secret
        secret:
          secretName: pachyderm-storage-secret
status: {}
```

**Anything else we need to know?**:

**Environment?**:
- Kubernetes version (use `kubectl version`):
- Pachyderm CLI and pachd server version (use `pachctl version`): 1.11.8
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s): aws
- OS (e.g. from /etc/os-release):
- Others:
