### ISSUE TITLE
Join with Multiple Capture Croups Not Working Correctly

### ISSUE THREAD

**Issue by dgeorg42** [pachyderm/pachyderm#6675]
This customer scenario works on 1.13.2, but not on 2.0 Beta 5.

The pipeline spec for `dualfan_data_location_group` has a JOIN defined as follows:
```
  join:
  - pfs:
      empty_files: true
      glob: /dualfan/(*)/(*)/(*)
      joinOn: $1/$2/$3
      name: DATA_PATH
      outer_join: true
      repo: data_source_dualfan_linkmerge
  - pfs:
      empty_files: true
      glob: /dualfan/(*)/(*)/(*)
      joinOn: $1/$2/$3
      name: LOCATION_PATH
      repo: dualfan_location_asset_assignment
```

The `data_source_dualfan_linkmerge` repo has 5 directories that match its glob pattern:
```
NAME                 TAG TYPE     SIZE 
/dualfan/2020/01/01/ dir 2.232MiB 
/dualfan/2020/01/02/ dir 2.194MiB 
/dualfan/2020/01/03/ dir 2.209MiB 
/dualfan/2020/01/04/ dir 2.196MiB 
/dualfan/2020/01/05/ dir 2.285MiB 
```

The `dualfan_location_asset_assignment` has those same 5 directories, but also 361 more (total of 366) that match _its_ glob pattern.

The result of the join should be 5 datums that match the 5 directories in `data_source_dualfan_linkmerge` with the corresponding 5 directories in `dualfan_location_asset_assignment` - and, in fact, this is what we see in 1.13 when the job runs:
```
82e24c9618b4449e8cff44a82b3ff5ea dualfan_data_location_group        About a minute ago 14 seconds 0       5 + 0 / 5     0B       0B       success 
```

However, on 2.0, the JOIN produces 1,830 datums:
```
9c34c058cb774e52ad915abb0a4e1239 dualfan_data_location_group        20 minutes ago 9 minutes          0       1830 + 0 / 1830 0B       0B       success 
```

Not coincidentally, 5 * 366 = 1,830; in other words, the result we're getting is as if we did a CROSS rather than a JOIN.

Further confirmation of this can be found by inspecting one of the datums:
```
ID	ffa73134bf8c36b80fccaeee583af4d955881d0b277e371c59a3d653e756dd81
Job ID	dcc25eb0fdf94e8fa4b8d4601b7de096
State	SUCCESS
Data Downloaded	0B
Data Uploaded	0B
Total Time	243.063559ms
Download Time	113.881279ms
Process Time	123.594903ms
Upload Time	5.587377ms
PFS State:
  REPO                               COMMIT                             PATH                                                                    
  dualfan_data_location_group.meta   dcc25eb0fdf94e8fa4b8d4601b7de096   /pfs/ffa73134bf8c36b80fccaeee583af4d955881d0b277e371c59a3d653e756dd81   
Inputs:
  REPO                                COMMIT                             PATH                   
  data_source_dualfan_linkmerge       dcc25eb0fdf94e8fa4b8d4601b7de096   /dualfan/2020/01/01/   
  dualfan_location_asset_assignment   dcc25eb0fdf94e8fa4b8d4601b7de096   /dualfan/2020/03/22/   
```
where you can see that the two files in the datum should not have been joined.

[AB#42](https://dev.azure.com/PachydermCompany/92b98a32-88e5-46cb-a28f-5d064712e03b/_workitems/edit/42)
