### ISSUE TITLE
Impossible to upgrade Pachyderm cluster from 2.0.0 to 2.0.4

### ISSUE THREAD

**Issue by quematech** [pachyderm/pachyderm#7211]
**What happened?**:

We tried to upgrade a pachyderm cluster from 2.0.0 to 2.0.4, following the webpage : 
https://docs.pachyderm.com/latest/deploy-manage/manage/upgrades/

We could upgrade the pachctl client without any problem. However, when trying to to the helm upgrade, we met some problems. I think it's a trivial problem with the Helm values.yaml file, however, I do not understand how to solve it.

We updated our values.yaml file as below : 
```

deployTarget: "GOOGLE"

global:
  postgresql.postgresqlPassword: ""
  
pachd:
  clusterDeploymentID: ""
  rootToken: ""
  enterpriseSecret: ""
  oauthClientSecret: ""

  storage:
    google:
      bucket: "BUCKET NAME"
      cred: |
        JSON CRED

  externalService:
    enabled: true
```

Values are all empty, as they look this way in a helm get all.

However, launching the following command : 

`helm upgrade pachyderm -f values.yaml pach/pachyderm --version 2.0.4`

Gives us : 

`Error: UPGRADE FAILED: execution error at (pachyderm/charts/postgresql/templates/secrets.yaml:15:35): During an upgrade, global.postgresql.postgresqlPostgresPassword must be set. To retrieve the value generated on install, run: `kubectl get secret postgres -o yaml | grep postgresql-postgres-password | awk  '{print $2}' | base64 -d``

We tried the following steps : 
* Renaming postgresql.postgresqlPassword to postgresql.postgresqlPostgresPassword in the values.yaml
* Adding directly the variable in the command : 
`helm upgrade pachyderm -f values.yaml pach/pachyderm --version 2.0.4 --set global.postgresql.postgresqlPostgresPassword=""`

Nothing worked :/

**What you expected to happen?**:

For the upgrade to process

**Environment?**:
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f", GitTreeState:"clean", BuildDate:"2021-03-18T01:10:43Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5-gke.1302", GitCommit:"639f3a74abf258418493e9b75f2f98a08da29733", GitTreeState:"clean", BuildDate:"2021-10-21T21:35:48Z", GoVersion:"go1.16.7b7", Compiler:"gc", Platform:"linux/amd64"}

```
- Pachyderm CLI and pachd server version (use `pachctl version`):

```
COMPONENT           VERSION             
pachctl             2.0.4               
pachd               2.0.0
```

- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):

GKE

- If you deployed with helm, the values you used (`helm get values pachyderm`):

```
USER-SUPPLIED VALUES:
deployTarget: GOOGLE
pachd:
  externalService:
    enabled: true
  storage:
    google:
      bucket: BUCKET-NAME
      cred: |
        JSON
```

- OS (e.g. from /etc/os-release):

```
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

- Others:

Happy christmas

**Comment by tybritten** [comment]
Hi!
The formatting of your Postgres password section is wrong. It should be:

```
global:
  postgresql:
    postgresqlPassword: <value>

```

**Comment by quematech** [comment]
Hi

Thank you a lot for your fast answer. However, this formatting gives the very same error. By the way, do we agree that by itself, the postgresql password is an empty string ? : 

values.yaml file : 

```
deployTarget: "GOOGLE"

global:
  postgresql:
    postgresqlPassword: ""
  
pachd:
  clusterDeploymentID: ""
  rootToken: ""
  enterpriseSecret: ""
  oauthClientSecret: ""
  storage:
    google:
      bucket: "BUCKET"
      cred: |
        JSON

  externalService:
    enabled: true
```

Output : 

` helm upgrade pachyderm -f values.yaml pach/pachyderm`

`Error: UPGRADE FAILED: execution error at (pachyderm/charts/postgresql/templates/secrets.yaml:15:35): During an upgrade, global.postgresql.postgresqlPostgresPassword must be set. To retrieve the value generated on install, run: kubectl get secret postgres -o yaml | grep postgresql-postgres-password | awk  '{print $2}' | base64 -d`

Thank you a lot for your insights, and Best Regards

E
