### ISSUE TITLE
put file failed behind a proxy

### ISSUE THREAD

**Issue by markqiu** [pachyderm/pachyderm#7939]
**What happened?**:
pachctl put file images_clever-stegodon@master:birthday-cake.jpg -f https://i.imgur.com/FOO9q43.jpg
Get "https://i.imgur.com/FOO9q43.jpg": dial tcp 103.230.123.190:443: i/o timeout
**What you expected to happen?**:
I have set HTTP_PROXY HTTPS_PROXY environment variable correctly.
**How to reproduce it (as minimally and precisely as possible)?**:
rerun the command
**Anything else we need to know?**:
How to set a proxy for pachctl?
**Environment?**:
- Kubernetes version (use `kubectl version`):
- Pachyderm CLI and pachd server version (use `pachctl version`):
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
- If you deployed with helm, the values you used (`helm get values pachyderm`):
- OS (e.g. from /etc/os-release):
- Others:

**Comment by jrockway** [comment]
Not 100% sure what your setup is, but the GET is actually done by the pachd server, so these environment variables need to be set on the server.  The helm value `global.proxy` defines the proxy to use.  (There is also `noProxy` that sets the `$NO_PROXY` environment variable.)

**Comment by markqiu** [comment]
Thank you for your response. Tried that, the environment variables are set now, but the pod is not ready now.
![image](https://user-images.githubusercontent.com/1124637/180160012-ed520226-1eca-43d9-972c-5d804fa1fccc.png)
Error logs:
```
internal/poll.(*pollDesc).wait(0xc00131c200, 0xc001214000, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc00131c200, {0xc001214000, 0x1000, 0x1000})
	/usr/local/go/src/internal/poll/fd_unix.go:167 +0x25a
net.(*netFD).Read(0xc00131c200, {0xc001214000, 0x0, 0x0})
	/usr/local/go/src/net/fd_posix.go:56 +0x29
net.(*conn).Read(0xc000a5e060, {0xc001214000, 0xc001034680, 0x4})
	/usr/local/go/src/net/net.go:183 +0x45
bufio.(*Reader).Read(0xc000a58480, {0xc00131e2e0, 0x5, 0x3})
	/usr/local/go/src/bufio/bufio.go:227 +0x1b4
io.ReadAtLeast({0x3447560, 0xc000a58480}, {0xc00131e2e0, 0x5, 0x200}, 0x5)
	/usr/local/go/src/io/io.go:328 +0x9a
io.ReadFull(...)
	/usr/local/go/src/io/io.go:347
github.com/lib/pq.(*conn).recvMessage(0xc00131e2c0, 0xc000e16750)
	/home/circleci/go/pkg/mod/github.com/lib/pq@v1.10.2/conn.go:983 +0xca
github.com/lib/pq.(*ListenerConn).listenerConnLoop(0xc000744080)
	/home/circleci/go/pkg/mod/github.com/lib/pq@v1.10.2/notify.go:196 +0xab
github.com/lib/pq.(*ListenerConn).listenerConnMain(0xc000744080)
	/home/circleci/go/pkg/mod/github.com/lib/pq@v1.10.2/notify.go:249 +0x25
created by github.com/lib/pq.newDialListenerConn
	/home/circleci/go/pkg/mod/github.com/lib/pq@v1.10.2/notify.go:138 +0x127
goroutine 339 [select]:
github.com/pachyderm/pachyderm/v2/src/internal/collection.(*postgresWatcher).forwardNotifications(0xc0009a23c0, {0x34b3310, 0xc000a22680})
	src/internal/collection/postgres_listener.go:114 +0xff
github.com/pachyderm/pachyderm/v2/src/internal/collection.(*postgresReadOnlyCollection).watchRoutine(0xc0009f8540, 0xc0009a23c0, {0x0, 0x0, 0x0, 0x0}, 0x0)
	src/internal/collection/postgres_collection.go:584 +0x245
created by github.com/pachyderm/pachyderm/v2/src/internal/collection.(*postgresReadOnlyCollection).watchOne
	src/internal/collection/postgres_collection.go:636 +0x22f
goroutine 341 [select]:
github.com/pachyderm/pachyderm/v2/src/internal/collection.(*postgresWatcher).forwardNotifications(0xc000b3da40, {0x34b3310, 0xc000a22680})
	src/internal/collection/postgres_listener.go:114 +0xff
github.com/pachyderm/pachyderm/v2/src/internal/collection.(*postgresReadOnlyCollection).watchRoutine(0xc0009f8558, 0xc000b3da40, {0x0, 0x0, 0x0, 0x0}, 0x0)
	src/internal/collection/postgres_collection.go:584 +0x245
created by github.com/pachyderm/pachyderm/v2/src/internal/collection.(*postgresReadOnlyCollection).watchOne
	src/internal/collection/postgres_collection.go:636 +0x22f
error setting up External Pachd GRPC Server: error setting up PFS API GRPC Server: unable to write to object storage: 503 Service Unavailable
```

**Comment by markqiu** [comment]
It works now. I solved the probelm by adding "local" to the noProxy variable. Thanks again! @jrockway

**Comment by markqiu** [comment]
Sorry, wrong again.
The console cannot be accessed now, and the error message in the log is as follows. It should be necessary to add some noProxys.
My  values.yaml is as follows:
```yaml
# SPDX-FileCopyrightText: Pachyderm, Inc. <info@pachyderm.com>
# SPDX-License-Identifier: Apache-2.0
deployTarget: "MINIO"

global:
 # Sets the HTTP/S proxy server address for console, pachd, and enteprise server
  proxy: "http://123.103.74.231:20172"
  # If proxy is set, this allows you to set a comma-separated list of destinations that bypass the proxy
  noProxy: "10.1.0.0/16,10.152.183.0/24,localhost,jinniuai,127.0.0.1,172.16.0.0/15,192.168.0.0/16,jinniuai.internal,hub,jinniuai.com,local,postgresql,minio,postgres-0,pachd,etcd-0,etcd,console,pachd-peer,postgres-headless,etcd-headless,pg-bouncer"

pachd:
  storage:
    backend: "MINIO"
    minio:
      bucket: "pachyderm"
      endpoint: "minio.minio.svc.cluster.local:9000"
      id: "rootuser"
      secret: "rootpass123"
      secure: "false"
etcd:
  storageClass: openebs-hostpath
  size: 10Gi

postgresql:
  persistence:
    storageClass: openebs-hostpath
    size: 10Gi
```
My installation command is as follow:
```shell
 microk8s helm3 upgrade --install pachd -f pachyderm-enterprise-member-values.yaml pach/pachyderm --set pachd.enterpriseLicenseKey=$(cat pachyderm-enterprise-license.txt) --namespace pachyderm --create-namespace --set console.enabled=true
```

The error in the log is as follows:
```text
dotenv-flow: "REACT_APP_RUNTIME_ISSUER_URI" is already defined in `process.env` and will not be overwritten
dotenv-flow: "REACT_APP_RUNTIME_SUBSCRIPTIONS_PREFIX" is already defined in `process.env` and will not be overwritten
dotenv-flow: "REACT_APP_RUNTIME_DISABLE_TELEMETRY" is already defined in `process.env` and will not be overwritten
dotenv-flow: "ISSUER_URI" is already defined in `process.env` and will not be overwritten
dotenv-flow: "OAUTH_REDIRECT_URI" is already defined in `process.env` and will not be overwritten
dotenv-flow: "OAUTH_CLIENT_ID" is already defined in `process.env` and will not be overwritten
dotenv-flow: "OAUTH_CLIENT_SECRET" is already defined in `process.env` and will not be overwritten
dotenv-flow: "GRAPHQL_PORT" is already defined in `process.env` and will not be overwritten
dotenv-flow: "OAUTH_PACHD_CLIENT_ID" is already defined in `process.env` and will not be overwritten
dotenv-flow: "PACHD_ADDRESS" is already defined in `process.env` and will not be overwritten
Persisted queries are enabled and are using an unbounded cache. Your server is vulnerable to denial of service attacks via memory exhaustion. Set `cache: "bounded"` or `persistedQueries: false` in your ApolloServer constructor, or see https://go.apollo.dev/s/cache-backends for other alternatives.
{"name":"dash-api","hostname":"console-7454cc697f-slncz","pid":18,"level":30,"msg":"Server ready at https://localhost:4000/graphql","time":"2022-07-21T11:31:06.042Z","v":0}
{"name":"dash-api","hostname":"console-7454cc697f-slncz","pid":18,"level":30,"msg":"Websocket server ready at wss://localhost:4000/graphql","time":"2022-07-21T11:31:06.080Z","v":0}
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error: 14 UNAVAILABLE: Connection dropped
    at Object.callErrorFromStatus (/usr/src/app/backend/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
    at Object.onReceiveStatus (/usr/src/app/backend/node_modules/@grpc/grpc-js/build/src/client.js:180:52)
    at Object.onReceiveStatus (/usr/src/app/backend/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:365:141)
    at Object.onReceiveStatus (/usr/src/app/backend/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:328:181)
    at /usr/src/app/backend/node_modules/@grpc/grpc-js/build/src/call-stream.js:187:78
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
{"name":"dash-api","hostname":"console-7454cc697f-slncz","pid":18,"eventSource":"grpc client","pachdAddress":"pachd-peer.pachyderm.svc.cluster.local:30653","level":30,"msg":"Creating pach client","time":"2022-07-21T11:42:44.636Z","v":0}
{"name":"dash-api","hostname":"console-7454cc697f-slncz","pid":18,"eventSource":"grpc client","pachdAddress":"pachd-peer.pachyderm.svc.cluster.local:30653","level":30,"msg":"whoAmI request started","time":"2022-07-21T11:42:44.637Z","v":0}
{"name":"dash-api","hostname":"console-7454cc697f-slncz","pid":18,"eventSource":"grpc client","pachdAddress":"pachd-peer.pachyderm.svc.cluster.local:30653","level":50,"error":"Connection dropped","msg":"whoAmI request failed","time":"2022-07-21T11:42:46.797Z","v":0}
{"name":"dash-api","hostname":"console-7454cc697f-slncz","pid":18,"eventSource":"grpc client","pachdAddress":"pachd-peer.pachyderm.svc.cluster.local:30653","level":30,"msg":"whoAmI request started","time":"2022-07-21T11:42:47.022Z","v":0}
{"name":"dash-api","hostname":"console-7454cc697f-slncz","pid":18,"eventSource":"grpc client","pachdAddress":"pachd-peer.pachyderm.svc.cluster.local:30653","level":50,"error":"Connection dropped","msg":"whoAmI request failed","time":"2022-07-21T11:42:49.494Z","v":0}
{"name":"dash-api","hostname":"console-7454cc697f-slncz","pid":18,"eventSource":"grpc client","pachdAddress":"pachd-peer.pachyderm.svc.cluster.local:30653","level":30,"msg":"whoAmI request started","time":"2022-07-21T11:42:50.796Z","v":0}
{"name":"dash-api","hostname":"console-7454cc697f-slncz","pid":18,"eventSource":"grpc client","pachdAddress":"pachd-peer.pachyderm.svc.cluster.local:30653","level":50,"error":"Connection dropped","msg":"whoAmI request failed","time":"2022-07-21T11:42:52.951Z","v":0}
{"name":"dash-api","hostname":"console-7454cc697f-slncz","pid":18,"eventSource":"grpc client","pachdAddress":"pachd-peer.pachyderm.svc.cluster.local:30653","level":30,"msg":"whoAmI request started","time":"2022-07-21T11:42:53.766Z","v":0}
{"name":"dash-api","hostname":"console-7454cc697f-slncz","pid":18,"eventSource":"grpc client","pachdAddress":"pachd-peer.pachyderm.svc.cluster.local:30653","level":50,"error":"Connection dropped","msg":"whoAmI request failed","time":"2022-07-21T11:42:56.955Z","v":0}
{"name":"dash-api","hostname":"console-7454cc697f-slncz","pid":18,"eventSource":"grpc client","pachdAddress":"pachd-peer.pachyderm.svc.cluster.local:30653","level":30,"msg":"whoAmI request started","time":"2022-07-21T11:42:59.830Z","v":0}
{"name":"dash-api","hostname":"console-7454cc697f-slncz","pid":18,"eventSource":"grpc client","pachdAddress":"pachd-peer.pachyderm.svc.cluster.local:30653","level":50,"error":"Connection dropped","msg":"whoAmI request failed","time":"2022-07-21T11:43:01.995Z","v":0}
```
@jrockway

**Comment by jrockway** [comment]
It looks like the grpc library does an exact comparison on the host being connected to, without the port.  Since PACHD_ADDRESS is `pachd-peer.default.svc.cluster.local:30658`, `noProxy` needs to contain `pachd-peer.default.svc.cluster.local`.

If that doesn't work, you can do some more extreme debugging of console; `kubectl edit deployment console` and then add these environment variables:

```yaml                                                                                                                                                                                                                                                - name: GRPC_TRACE
   value: proxy
- name: GRPC_VERBOSITY
   value: DEBUG
```
 
That should print something like:
```
D 2022-07-22T02:14:09.498Z | proxy | Proxy server 127.0.0.1:80 set by environment variable https_proxy                                                                                                                                                   D 2022-07-22T02:14:09.499Z | proxy | No proxy server list set by environment variable no_proxy                                                                                                                                                           D 2022-07-22T02:14:09.499Z | proxy | Not using proxy for target in no_proxy list: dns:pachd-peer.default.svc.cluster.local:30653                                                                                                                         
```
