### ISSUE TITLE
Spout pipeline can't be restarted

### ISSUE THREAD

**Issue by defiori** [pachyderm/pachyderm#8303]
**What happened?**:
After stopping a spout pipeline with 
`pachctl stop pipeline spout-test`
attempting to restart with
`pachctl start pipeline spout-test`
produces the following error
`error from StartPipeline: repo spout-test.meta not found`

**What you expected to happen?**:
The spout pipeline should restart.

**How to reproduce it (as minimally and precisely as possible)?**:
- Create a spout pipeline, `pachctl create pipeline -f spout-test.yaml`:
```
# spout-test.yaml
pipeline:
  name: spout-test
spout: {}
transform:
  image: public.ecr.aws/docker/library/python:3.8-slim
  cmd:
  - python3
  - '-'
  stdin:
  - |
    import time
    if __name__ == "__main__":
        while True:
            time.sleep(3)
            print('Tick')
```
- Pause it with `pachctl stop pipeline spout-test`
- Attempt to restart with `pachctl start pipeline spout-test`

**Environment?**:
- Kubernetes version (use `kubectl version`): v1.25.2
- Pachyderm CLI and pachd server version (use `pachctl version`): v2.2.7
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s): local kind cluster
- If you deployed with helm, the values you used (`helm get values pachyderm`):
`helm install pachd pach/pachyderm -f pachyderm-helm-local.yaml --version 2.2.7`
```
# pachyderm-helm-local.yaml
deployTarget: "LOCAL"
pachd:
  enabled: true
postgresql:
  enabled: true
```
- OS (e.g. from /etc/os-release): Ubuntu 20.04.4
