### ISSUE TITLE
console does not load

### ISSUE THREAD

**Issue by RaananHadar** [pachyderm/pachyderm#9855]
**What happened?**:
I tried to upgrade pachyderm to the latest version and can't connect to console.

**What you expected to happen?**:
console should load.

**How to reproduce it (as minimally and precisely as possible)?**:
upgrade to any pachyderm/haberdashery image newer or equal to 2.8.3

**Anything else we need to know?**:
I tried going back versions and got multiple different errors. The first working version is 2.8.2

**Environment?**:
- Pachyderm CLI and pachd server version (use `pachctl version`): 2.9.2
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s): Azure
- If you deployed with helm, the values you used (`helm get values pachyderm`):
```
 deployTarget: "MICROSOFT"
 proxy:
  enabled: true
  service:
    type: ClusterIP
 pachd:
   image:
     repository: "pachyderm/pachd"
     tag: "2.9.2"
   worker:
     image:
       repository: "pachyderm/worker"
   storage:
     microsoft:
       # storage container name
       container: "container-name"
       # storage account name
       id: "storage-account-name"
       # storage account key
       secret: "secret"
   externalService:
     enabled: false
 console:
   enabled: true
   image:
     repository: "pachyderm/haberdashery"
     tag: "2.8.3"
 etcd:
   storageSize: 256Gi
```
